insert into authors (id, first_name, last_name) values (1, 'Miof mela', 'Pastor');
insert into authors (id, first_name, last_name) values (2, 'Karissa', 'Licciardiello');
insert into authors (id, first_name, last_name) values (3, 'Kendra', 'Bakewell');
insert into authors (id, first_name, last_name) values (4, 'Wolfie', 'Lillow');
insert into authors (id, first_name, last_name) values (5, 'Marilee', 'Mayman');
insert into authors (id, first_name, last_name) values (6, 'Sean', 'Deverell');
insert into authors (id, first_name, last_name) values (7, 'Shara', 'Krop');
insert into authors (id, first_name, last_name) values (8, 'Creight', 'MacCrann');
insert into authors (id, first_name, last_name) values (9, 'Stefano', 'Romme');
insert into authors (id, first_name, last_name) values (10, 'Debor', 'Whoston');
insert into authors (id, first_name, last_name) values (11, 'Ingaborg', 'Choupin');
insert into authors (id, first_name, last_name) values (12, 'Rodolphe', 'Siflet');
insert into authors (id, first_name, last_name) values (13, 'Christin', 'Shearme');
insert into authors (id, first_name, last_name) values (14, 'Shirley', 'Dmitrienko');
insert into authors (id, first_name, last_name) values (15, 'Kalle', 'de Pinna');
insert into authors (id, first_name, last_name) values (16, 'Wendye', 'McCulley');
insert into authors (id, first_name, last_name) values (17, 'Giorgia', 'Summerlad');
insert into authors (id, first_name, last_name) values (18, 'Livvyy', 'Skeldinge');
insert into authors (id, first_name, last_name) values (19, 'Luelle', 'McKue');
insert into authors (id, first_name, last_name) values (20, 'Robin', 'Sirmond');
insert into authors (id, first_name, last_name) values (21, 'Giles', 'Langsbury');

insert into books (id, price, price_old, title, author_id) values (1, 1560, 3400, 'Flowdesk', 9);
insert into books (id, price, price_old, title, author_id) values (2, 882, 3159, 'Stringtough', 1);
insert into books (id, price, price_old, title, author_id) values (3, 2366, 1207, 'Stronghold', 1);
insert into books (id, price, price_old, title, author_id) values (4, 2440, 3261, 'Daltfresh', 13);
insert into books (id, price, price_old, title, author_id) values (5, 2971, 1662, 'Viva', 15);
insert into books (id, price, price_old, title, author_id) values (6, 1748, 1512, 'Holdlamis', 19);
insert into books (id, price, price_old, title, author_id) values (7, 2487, 2895, 'Wrapsafe', 19);
insert into books (id, price, price_old, title, author_id) values (8, 1364, 3572, 'Latlux', 2);
insert into books (id, price, price_old, title, author_id) values (9, 2946, 1262, 'Sub-Ex', 21);
insert into books (id, price, price_old, title, author_id) values (10, 1046, 2561, 'Daltfresh', 4);
insert into books (id, price, price_old, title, author_id) values (11, 1283, 1852, 'Hatity', 18);
insert into books (id, price, price_old, title, author_id) values (12, 1923, 3931, 'Rank', 1);
insert into books (id, price, price_old, title, author_id) values (13, 580, 1941, 'Stringtough', 20);
insert into books (id, price, price_old, title, author_id) values (14, 2616, 1057, 'Tin', 15);
insert into books (id, price, price_old, title, author_id) values (15, 817, 1615, 'Matsoft', 4);
insert into books (id, price, price_old, title, author_id) values (16, 1945, 2512, 'Tresom', 6);
insert into books (id, price, price_old, title, author_id) values (17, 2735, 1744, 'Viva', 6);
insert into books (id, price, price_old, title, author_id) values (18, 2641, 3121, 'Solarbreeze', 6);
insert into books (id, price, price_old, title, author_id) values (19, 2508, 3978, 'Mat Lam Tam', 3);
insert into books (id, price, price_old, title, author_id) values (20, 906, 3943, 'Voyatouch', 1);
insert into books (id, price, price_old, title, author_id) values (21, 2394, 2319, 'Zontrax', 4);
